// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZlHj6dkermb33BaWOj8LkoBVLSU302A',
    appId: '1:773298568818:android:b65fce45fbe81151e0cceb',
    messagingSenderId: '773298568818',
    projectId: 'triviaapp-tt',
    storageBucket: 'triviaapp-tt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo747R3vYayt7r4zd0tt5JNqM94RyFuIc',
    appId: '1:773298568818:ios:c76902bf550cdd10e0cceb',
    messagingSenderId: '773298568818',
    projectId: 'triviaapp-tt',
    storageBucket: 'triviaapp-tt.firebasestorage.app',
    iosBundleId: 'TriviaApp.com.triviaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBn8AG7Zgu6zl-k6we1wqeBC6yYcB9_Qs',
    appId: '1:773298568818:web:59be015e3f2da9cde0cceb',
    messagingSenderId: '773298568818',
    projectId: 'triviaapp-tt',
    authDomain: 'triviaapp-tt.firebaseapp.com',
    storageBucket: 'triviaapp-tt.firebasestorage.app',
    measurementId: 'G-ST3TG7TETT',
  );
}
